### PR TITLE
Update backend deps and fix to match devtools API

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Comment by brandones** [comment]
For some reason I'm still not getting messages about missing dependencies in the devtools (when I add a non-existent entry like `fhir: "2.0.0"` to the dependencies list and have esm-api in the overrides). Maybe the devtools backend dependency checker doesn't work if the module is overridden? @fatmali ?

Anyway, this doesn't break anything.

**Comment by fatmali** [comment]
@brandones it should work even when overridden. Do you get notifications if you use a 1.x.x version?

**Review by fatmali — APPROVED** [review]

**Comment by brandones** [comment]
fhir2 is on 1.0.0-SNAPSHOT. So to test this out I changed the dependency to `fhir2: "2.0.0"`. No messages. Neither for the fake dependency `foo: "1.0.0"`.

**Comment by fatmali** [comment]
Something probably broke on this one, Donald worked on this with me @dkibet is the backend dependency feature working as expected?

**Comment by brandones** [comment]
@donaldkibet , question from Fatma:

> is the backend dependency feature working as expected?

**Comment by donaldkibet** [comment]
> @donaldkibet , question from Fatma:
> 
> > is the backend dependency feature working as expected?

It is only working as expected on patient-chart and patient-chart-widgets modules only.

**Comment by brandones** [comment]
@donaldkibet , cool, do you have any idea why?

**Comment by brandones** [comment]
@donaldkibet , can we have a call sometime soon to investigate this?

**Comment by donaldkibet** [comment]
> @donaldkibet , can we have a call sometime soon to investigate this?

sure @brandones  what time works best for you

**Comment by brandones** [comment]
Following up via DM...

**Comment by brandones** [comment]
I'm going to merge this, we should do more debugging of devtools outside this PR.

**Pull request merged**
