### PR TITLE
migrated to fhir 2

### PR DESCRIPTION
**Pull request by nkimaina**

### CODE REVIEW

**Comment by brandones** [comment]
So what's the plan? We merge this, version bump (minor?), update the dep in the MFEs, and start assessing for bugs?

**Comment by brandones** [comment]
Ah, I see your comment in Slack! Sounds good.

**Review by brandones — APPROVED** [review]

**Comment by nkimaina** [comment]
@brandones Yes, we will need to release the changes in a minor version, to npm, so that https://github.com/openmrs/openmrs-esm-patient-chart-widgets/pull/35 is fixed. Are you able to do that?

**Review by jonathandick — APPROVED** [review]

**Comment by brandones** [comment]
@nkimaina , sorry I missed this! Yes, will release.

**Comment by brandones** [comment]
@nkimaina  @jonathandick  Wait... is this a minor version, or is it a breaking change? This seems like a breaking change.

**Comment by brandones** [comment]
Releasing as breaking change.

**Pull request merged**
